import React from 'react';
import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import OrganizerCheckInPage from '../page';
import { checkInTicket, parseQrPayload, resetCheckInState, buildTicketQrPayload, getTicketById } from '@/lib/tickets';

// Mock html5-qrcode library
vi.mock('html5-qrcode', () => {
  return {
    Html5Qrcode: vi.fn().mockImplementation(() => ({
      start: vi.fn().mockResolvedValue(undefined),
      stop: vi.fn().mockResolvedValue(undefined),
      clear: vi.fn().mockReturnValue(undefined),
      isScanning: false,
    })),
  };
});

// Mock next/image
vi.mock('next/image', () => ({
  __esModule: true,
  default: (props: React.ImgHTMLAttributes<HTMLImageElement> & { src: unknown }) => {
    // eslint-disable-next-line @next/next/no-img-element
    return <img {...props} src={typeof props.src === 'string' ? props.src : '/mock-logo.png'} alt={props.alt || ''} />;
  },
}));

// Mock Stellar Wallet Hook
vi.mock('@/hooks/useStellarWallet', () => ({
  useStellarWallet: () => ({
    publicKey: 'GORGANIZER123456789',
    connect: vi.fn(),
    isConnecting: false,
  }),
}));

describe('Organizer Check-In & Ticket Verification', () => {
  beforeEach(() => {
    resetCheckInState();
    vi.clearAllMocks();
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  describe('QR Payload Parser (lib/tickets.ts)', () => {
    it('parses base64 encoded JSON QR payload generated by QRCodeModal', () => {
      const ticket = getTicketById('tkt-crypto-build-live')!;
      const rawPayload = buildTicketQrPayload(ticket);
      const parsed = parseQrPayload(rawPayload);

      expect(parsed).not.toBeNull();
      expect(parsed?.ticketId).toBe('tkt-crypto-build-live');
    });

    it('parses raw JSON QR payloads with ticketId or id', () => {
      const jsonPayload = JSON.stringify({
        ticketId: 'tkt-solana-vip',
        eventId: 'solana-summer-hackathon',
        signature: 'sig-xyz-123',
      });
      const parsed = parseQrPayload(jsonPayload);

      expect(parsed).not.toBeNull();
      expect(parsed?.ticketId).toBe('tkt-solana-vip');
      expect(parsed?.eventId).toBe('solana-summer-hackathon');
      expect(parsed?.signature).toBe('sig-xyz-123');
    });

    it('parses direct ticket ID strings', () => {
      const parsed = parseQrPayload('tkt-crypto-build-live');
      expect(parsed).not.toBeNull();
      expect(parsed?.ticketId).toBe('tkt-crypto-build-live');
    });

    it('rejects empty or malformed non-alphanumeric QR payloads', () => {
      expect(parseQrPayload('')).toBeNull();
      expect(parseQrPayload('   ')).toBeNull();
      expect(parseQrPayload('{invalid-json}')).toBeNull();
    });
  });

  describe('Authoritative Ticket Check-In (checkInTicket)', () => {
    it('successfully checks in a valid live ticket', () => {
      const result = checkInTicket('tkt-crypto-build-live');
      expect(result.success).toBe(true);
      expect(result.ticket?.checkedInAt).toBeDefined();
      expect(result.event?.id).toBe('crypto-build-ghana');
    });

    it('rejects duplicate check-in for an already consumed ticket', () => {
      // First check-in
      const firstResult = checkInTicket('tkt-crypto-build-live');
      expect(firstResult.success).toBe(true);

      // Second check-in attempt
      const secondResult = checkInTicket('tkt-crypto-build-live');
      expect(secondResult.success).toBe(false);
      expect(secondResult.reason).toBe('ALREADY_USED');
      expect(secondResult.error).toContain('Ticket Already Used');
    });

    it('rejects pre-existing used tickets (tkt-nairobi-used)', () => {
      const result = checkInTicket('tkt-nairobi-used');
      expect(result.success).toBe(false);
      expect(result.reason).toBe('ALREADY_USED');
    });

    it('rejects unknown or invalid tickets', () => {
      const result = checkInTicket('tkt-nonexistent-999');
      expect(result.success).toBe(false);
      expect(result.reason).toBe('INVALID_TICKET');
      expect(result.error).toContain('Invalid Ticket');
    });
  });

  describe('OrganizerCheckInPage UI Component', () => {
    it('renders the header, wallet indicator, and scanner mode toggle', () => {
      render(<OrganizerCheckInPage />);

      expect(screen.getByText(/Check-In Portal/i)).toBeInTheDocument();
      expect(screen.getByText(/GORG...6789/i)).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /Camera Scanner/i })).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /Manual Entry/i })).toBeInTheDocument();
    });

    it('switches between Camera Scanner and Manual Entry mode', async () => {
      render(<OrganizerCheckInPage />);

      const manualTab = screen.getByRole('button', { name: /Manual Entry/i });
      await userEvent.click(manualTab);

      expect(screen.getByLabelText(/Enter Ticket ID/i)).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /Check In Ticket/i })).toBeInTheDocument();
    });

    it('executes successful check-in via Manual Entry and shows green success card', async () => {
      vi.stubGlobal(
        'fetch',
        vi.fn(async () =>
          new Response(
            JSON.stringify({
              success: true,
              message: 'Check-in Successful — Valid Ticket',
              ticket: { id: 'tkt-crypto-build-live', eventId: 'crypto-build-ghana', ticketType: 'Regular' },
              event: { id: 'crypto-build-ghana', title: 'Crypto Build Ghana 2025' },
              checkedInAt: new Date().toISOString(),
            }),
            { status: 200 }
          )
        )
      );

      render(<OrganizerCheckInPage />);

      // Switch to manual mode
      await userEvent.click(screen.getByRole('button', { name: /Manual Entry/i }));

      // Enter valid ticket ID
      const input = screen.getByLabelText(/Enter Ticket ID/i);
      await userEvent.type(input, 'tkt-crypto-build-live');

      const submitBtn = screen.getByRole('button', { name: /Check In Ticket/i });
      await userEvent.click(submitBtn);

      // Verify Green Success UI appears
      expect(await screen.findByRole('heading', { name: /Check-in Successful/i })).toBeInTheDocument();
      expect(screen.getByText(/Valid Ticket/i)).toBeInTheDocument();
      expect(screen.getByText(/tkt-crypto-build-live/i)).toBeInTheDocument();
      expect(screen.getByRole('button', { name: /Scan Next Ticket/i })).toBeInTheDocument();
    });

    it('shows red failure card when ticket is already used', async () => {
      vi.stubGlobal(
        'fetch',
        vi.fn(async () =>
          new Response(
            JSON.stringify({
              success: false,
              reason: 'ALREADY_USED',
              error: 'Check-in Failed — Ticket Already Used',
              ticket: { id: 'tkt-nairobi-used', checkedInAt: '2026-08-10T10:00:00Z' },
            }),
            { status: 409 }
          )
        )
      );

      render(<OrganizerCheckInPage />);

      await userEvent.click(screen.getByRole('button', { name: /Manual Entry/i }));
      await userEvent.type(screen.getByLabelText(/Enter Ticket ID/i), 'tkt-nairobi-used');
      await userEvent.click(screen.getByRole('button', { name: /Check In Ticket/i }));

      // Verify Red Failure UI
      expect(await screen.findByRole('heading', { name: /Check-in Failed/i })).toBeInTheDocument();
      expect(screen.getByText(/Check-in Failed — Ticket Already Used/i)).toBeInTheDocument();
    });

    it('shows red failure card for invalid ticket ID', async () => {
      vi.stubGlobal(
        'fetch',
        vi.fn(async () =>
          new Response(
            JSON.stringify({
              success: false,
              reason: 'INVALID_TICKET',
              error: 'Check-in Failed — Invalid Ticket',
            }),
            { status: 404 }
          )
        )
      );

      render(<OrganizerCheckInPage />);

      await userEvent.click(screen.getByRole('button', { name: /Manual Entry/i }));
      await userEvent.type(screen.getByLabelText(/Enter Ticket ID/i), 'tkt-invalid-xyz');
      await userEvent.click(screen.getByRole('button', { name: /Check In Ticket/i }));

      expect(await screen.findByRole('heading', { name: /Check-in Failed/i })).toBeInTheDocument();
      expect(screen.getByText(/Check-in Failed — Invalid Ticket/i)).toBeInTheDocument();
    });

    it('handles offline mode by queuing check-in and showing pending status', async () => {
      // Simulate navigator offline
      Object.defineProperty(navigator, 'onLine', {
        configurable: true,
        value: false,
      });

      render(<OrganizerCheckInPage />);

      expect(screen.getByText(/Offline mode active/i)).toBeInTheDocument();

      await userEvent.click(screen.getByRole('button', { name: /Manual Entry/i }));
      await userEvent.type(screen.getByLabelText(/Enter Ticket ID/i), 'tkt-crypto-build-live');
      await userEvent.click(screen.getByRole('button', { name: /Check In Ticket/i }));

      // Verify Pending Offline UI appears (never false success)
      expect(await screen.findByText(/Check-in Pending Verification/i)).toBeInTheDocument();
      expect(screen.getByText(/Queued Offline/i)).toBeInTheDocument();
    });
  });
});
